var languageEN = {
	"ourBlog" : "blog",
	"ourApp" : "our app",
	"HowItWork": "how it works",
	"learningSources" : "sources for learning",
	"headerTitle" : "Learn a foreign language and open the world of new information",
	"headerSubtitle" : "With our mobile app",
	"buttonStarted" : "get started",
	"headPleasure" : "Learn languages with Pleasure",
	"contentPleasure" : "Any sources as <b>Netflix</b> and <b>Youtube</b> can be your lessons. You only need to find your favourite",
	"headMemory" : "All you have read or watched<br/>are clues for the memory",
	"contentMemory" : "Our training based on the materials you’ve learned before",
	"headOurApp" : "It is <span>EasyLang.app</span><sup>BETA</sup>",
	"contentOurApp" : "EasyLang is the <a class=\"openSoftware\" target=\"_blank\" href=\"https://en.wikipedia.org/wiki/Free_and_open-source_software\" id=\"openSource\">open-source</a> software.<br />Use it for FREE",
	"extension" : "for Chrome",
	"extensionGuide" : "Installation guide",
	"headHowItWorks" : "How does our app work?",
	"sliderCaptionFirst" : "Play some video",
	"sliderCaptionSecond" : "Click \"A\"(Add) button",
	"slideThird" : "<img src=\"img/slider/img/3.png\" alt=\"\">",
	"slideFourth" : "<img src=\"img/slider/img/4.png\" alt=\"\">",
	"blog" : "More you can find out at",
	"Blog" : "our blog",
	"headSource" : "What are the sources for learning?",
	"contentSource" : "Here you will find a few ideas",
	"music" : "music",
	"musicParagraph" : "Understand what are your favorite songs about",
	"news" : "news",
	"newsParagraph" : "Read the news without checking dictionaries",
	"video" : "video",
	"videoParagraph" : "Follow new bloggers on YouTube and other channels",
	"book" : "books",
	"bookParagraph" : "Start reading books in the original language",
	"movie" : "movie",
	"movieParagraph" : "Listen the original of your favorite movie characters",
	"getStarted" : "get started"
}