var languageRU = {
	"ourBlog" : "Наш блог",
	"ourApp" : "Приложение",
	"HowItWork": "Как пользоваться",
	"learningSources" : "Ресурсы",
	"headerTitle" : "Исследовать вселенную языков проще с EasyLang",
	"headerSubtitle" : "Попробуй EasyLang и начни своё комфорное обучение языкам",
	"buttonStarted" : "Начать",
	"headPleasure" : "Учи языки с удовольствием",
	"contentPleasure" : "Любой ресурс, как <b>Netflix</b> и <b>Youtube</b> может стать твоим уроком. Выбери свою любимую тематику и начни изучать.",
	"headMemory" : "Всё, что ты читаешь или видишь - это подсказки для твоей памяти",
	"contentMemory" : "Контекстное обучение EasyLang построено на материалах, которые ты изучал ранее",
	"headOurApp" : "<span> EasyLang.app <\/span> <sup> BETA <\/sup>",
	"contentOurApp" : "EasyLang это <a class=\"openSoftware\" target=\"_blank\" href=\"https://en.wikipedia.org/wiki/Free_and_open-source_software\" id=\"openSource\">open-source<\/a> проект. Использование абсолютно бесплатно",
	"extension" : "для Chrome",
	"extensionGuide" : "<i class=\"fa fa-cog\"> <\/i> Как установить",
	"headHowItWorks" : "Как учиться с EasyLang?",
	"sliderCaptionFirst" : "Включи любое видео",
	"sliderCaptionSecond" : "Нажми клавишу \"A\"(Add)",
	"slideThird" : "<img src=\"img/slider/svg/Illustration5-3.2.svg\" \/>",
	"slideFourth" : "<img src=\"img/slider/svg/Illustration5-4.2.svg\" \/>",
	"blog" : "Узнать больше в нашем",
	"Blog" : "блоге",
	"headSource" : "Где брать информацию для уроков?",
	"contentSource" : "У нас есть несколько идей для тебя",
	"music" : "музыка",
	"musicParagraph" : "Понимай о чём поётся в твоих любимых песнях",
	"news" : "Новости",
	"newsParagraph" : "Читай статьи и новости без словарей",
	"video" : "Видео",
	"videoParagraph" : "Подписывайся на блоггеров YouTube и другие платформы",
	"book" : "Книги",
	"bookParagraph" : "Читай книги в оригинале без перевода",
	"movie" : "Фильмы",
	"movieParagraph" : "Смотри фильмы без озвучивания на родном языке",
	"getStarted" : "Начать"
}